# Generated by Django 3.0.2 on 2020-01-18 02:01

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='about', verbose_name='Section-1 Image')),
                ('sec1_l1', models.CharField(max_length=255, verbose_name='Section-1 Text Line-1')),
                ('sec1_l2', models.CharField(max_length=255, verbose_name='Section-1 Text Line-2')),
                ('sec2_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='about', verbose_name='Section-2 Image')),
                ('about_l1', models.CharField(max_length=255, verbose_name='About Title')),
                ('about_l2', models.CharField(max_length=255, verbose_name='About Subtitle')),
                ('about', models.TextField()),
                ('sec3_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='about', verbose_name='Section-3 Image')),
                ('sec3_l1', models.CharField(max_length=255, verbose_name='Section-3 Title')),
                ('sec3_l2', models.CharField(max_length=255, verbose_name='Section-3 Subtitle')),
                ('sec3_paragraph', models.TextField()),
                ('sec4_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='about', verbose_name='Section-4 Image')),
                ('sec4_l1', models.CharField(max_length=255, verbose_name='Section-4 Text Line-1')),
                ('sec4_l2', models.CharField(max_length=255, verbose_name='Section-4 Text Line-2')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Company Name')),
                ('street', models.CharField(max_length=64, verbose_name='Street')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', models.CharField(max_length=25, verbose_name='State')),
                ('postal', models.CharField(max_length=6, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=25, null=True, verbose_name='Country')),
                ('address_map_link', models.TextField(blank=True, null=True, verbose_name='Google Maps link for the address')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='+90 (000) 000 00 00', max_length=30, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='example@email.com', max_length=128, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='contact', verbose_name='Section-1 Background Image')),
                ('sec1_l1', models.CharField(max_length=255, verbose_name='Section-1 Text Line-1')),
                ('sec1_l2', models.CharField(max_length=255, verbose_name='Section-1 Text Line-2')),
                ('sec3_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='about', verbose_name='Section-3 Background Image')),
                ('sec3_l1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-3 Text Line-1')),
                ('sec3_l2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-3 Text Line-2')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-1 Background Image')),
                ('header_title_line1', models.CharField(max_length=255, verbose_name='Section-1 Text Line-1')),
                ('header_title_line2', models.CharField(max_length=255, verbose_name='Section-1 Text Line-2')),
                ('section2', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='home', verbose_name='Section-2 Background Image')),
                ('section2_story', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='home', verbose_name='Section-2 Center-Box Background Image')),
                ('section2_image_left', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='home', verbose_name='Section-2 Left Image')),
                ('section2_image_right', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='home', verbose_name='Section-2 Right Image')),
                ('section2_title_line1', models.CharField(max_length=255, verbose_name='Section-2 Text Line-1')),
                ('section2_title_line2', models.CharField(max_length=255, verbose_name='Section-2 Text Line-2')),
                ('section3', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-3 Background Image')),
                ('section3_msg_line1', models.CharField(max_length=255, verbose_name='Section-3 Text Line-1')),
                ('section3_msg_line2', models.CharField(max_length=255, verbose_name='Section-3 Text Line-2')),
                ('section4_img1', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-4 Box-1 Image')),
                ('section4_img2', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-4 Box-2 Image')),
                ('section4_img3', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-4 Box-3 Image')),
                ('section4_img4', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-4 Box-4 Image')),
                ('section5', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-5 Background Image')),
                ('section5_msg_line1', models.CharField(max_length=255, verbose_name='Section-5 Text Line-1')),
                ('section5_msg_line2', models.CharField(max_length=255, verbose_name='Section-5 Text Line-2')),
                ('section6_img1', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-6 Image-1')),
                ('section6_img1_text_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-6 Image-1 Text Line 1')),
                ('section6_img1_text_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-6 Image-1 Text Line 2')),
                ('section6_img2', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-6 Image-2')),
                ('section6_img2_text_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-6 Image-2 Text Line 1')),
                ('section6_img2_text_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-6 Image-2 Text Line 2')),
                ('section6_img3', optimized_image.fields.OptimizedImageField(default='defaults/placeholder.png', upload_to='home', verbose_name='Section-6 Image-3')),
                ('section6_img3_text_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-6 Image-3 Text Line 1')),
                ('section6_img3_text_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section-6 Image-3 Text Line 3')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(help_text='eg. Chicken, Tomato, Egg', max_length=64, verbose_name='Ingredients')),
            ],
            options={
                'verbose_name': 'Ingredients',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', optimized_image.fields.OptimizedImageField(default='default_imgs/logo.png', upload_to='logo', verbose_name='Logo')),
                ('favicon', optimized_image.fields.OptimizedImageField(default='default_imgs/logo.png', upload_to='logo', verbose_name='Favicon 16x16')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_img', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='about', verbose_name='Section-1 Image')),
                ('sec1_l1', models.CharField(max_length=255, verbose_name='Section-1 Text Line-1')),
                ('sec1_l2', models.CharField(max_length=255, verbose_name='Section-1 Text Line-2')),
            ],
            options={
                'verbose_name': 'Menu Page',
                'verbose_name_plural': 'Menu Page',
            },
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_from', models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=12, null=True, verbose_name='From Day')),
                ('weekday_to', models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=12, null=True, verbose_name='To Day')),
                ('open_hr_from', models.CharField(blank=True, max_length=20, null=True, verbose_name='Open Hours From')),
                ('open_hr_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='Open Hours To')),
            ],
            options={
                'verbose_name': 'Open Hours',
                'verbose_name_plural': 'Open Hours',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('tripadvisor', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='eg. Adana Kebab. FIELD/ALAN: food_name', max_length=64, verbose_name='Food Name')),
                ('image', optimized_image.fields.OptimizedImageField(blank=True, default='defaults/noImage.jpg', null=True, upload_to='menu', verbose_name='Food Picture')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('feature', models.BooleanField(default=False, verbose_name='Feature On Home Page')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='ingredients', to='mySite.Ingredient', verbose_name='Ingredients In This Dish')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='eg. Lunch, Dessert, Drinks. FIELD/ALAN: category_name', max_length=64, unique=True, verbose_name='Category Name')),
                ('phrase_above_name', models.CharField(blank=True, help_text='eg. For Start, Tasty, More Concrete, Healthy, Refreshing etc. FIELD/ALAN: phrase_above_name', max_length=64, null=True, verbose_name='Phrase Above Category Name')),
                ('display_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True)),
                ('menu_items', models.ManyToManyField(related_name='category', to='mySite.Menu')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
